// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlghlhmcwwxdqujszaku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sZ2hsaG1jd3d4ZHF1anN6YWt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NDk5MjAsImV4cCI6MjA3NDQyNTkyMH0.riC_Vyb7jvs3_GiU6snTqGLZYytEnTySaZsfzE6TLHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});